# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18gNneVCMvX94PzRwS26uZy-izotWXFqI
"""

nl=[]
nne=int(input("Enter no of elements:- "))
for i in range(nne):
  nl.append(int(input("Enter a number:- ")))
nl.sort()
nthsmall=int(input("Enter which smallest number is needed:- "))
print(nl[nthsmall-1])

num=int(input("Enter a number which will be checked:- "))
rev=0
num2=num
while num > 0 :
  dig=num%10
  rev=rev*10+dig
  num= num//10
if rev== num2:
  print("The number is palindrome.")
else:
  print("The number is not a palindrome number.")

np=int(input("Enter How many pairs you want to add:-"))
pl=[]
for i in range(np):
  print("Pair ",(i+1))
  n1=int(input("Enter 1st element:-"))
  n2=int(input("Enter 2nd element:-"))
  pl.append((n1,n2))
print(pl)
ch=int(input("Enter the sum value for which the pair will be checked:-"))
rl=[]
for i in range(np):
  if pl[i][0]+pl[i][1]==ch:
    rl.append(pl[i])
print(rl)

num1 = int(input("Enter !st number:- "))
num2 = int(input("Enter 2nd number:- "))
ch=input("Enter choice ")
match ch:
  case '+':
    print(num1+num2)
  case '-':
    if num2>=num1:
      print(num2-num1)
    else:
      print(num1-num2)
  case '*':
    print(num1*num2)
  case '/':
    print(num1//num2)

p=int(input("Enter Principal:- "))
r=int(input("Enter Rate:- "))
n=int(input("Enter No of times compounded:- "))
nt=int(input("Enter years:- "))
amount= (p*(1+(r//n)))**nt
ci=amount-p
print("The Interest is :-",(ci))

num=int(input("Enter a number"))
n=2
count=2
for i in range(n,num):
  if num%n==0:
    count=count+1
if num==1:
  print("Nor prime nor Composite")
elif count>2:
  print("Not a Prime No")
else:
  print("Prime No")

def cal(num1,num2):